---
- name: Wait for SSH to come up
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 60
    timeout: 320
    state: started

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
    autoclean: yes
    autoremove: yes

- name: Create a new user
  user:
    name: "{{ new_username }}"
    password: "{{ new_user_password | password_hash('sha512') }}"
    groups: sudo
    append: yes

- name: Disable root user
  user:
    name: root
    shell: /usr/sbin/nologin

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: Allow only the new user to login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers'
    line: 'AllowUsers {{ new_username }}'
    state: present

- name: Restart SSH service
  service:
    name: ssh
    state: restarted

- name: Install git, curl, wget, docker, docker-compose, screen
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - wget
    - docker.io
    - docker-compose
    - screen

- name: Add new user to docker group
  user:
    name: "{{ new_username }}"
    groups: docker
    append: yes

- name: Ensure docker service is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Install latest Golang
  become: yes
  shell: >
    wget -O go.tar.gz https://golang.org/dl/go{{ lookup('env', 'GO_VERSION') }}.linux-amd64.tar.gz &&
    sudo tar -C /usr/local -xzf go.tar.gz &&
    rm go.tar.gz

- name: Add Golang to PATH
  become: yes
  lineinfile:
    dest: /home/{{ new_username }}/.bashrc
    line: 'export PATH=$PATH:/usr/local/go/bin'
    owner: "{{ new_username }}"
    group: "{{ new_username }}"
    mode: '0755'

- name: Run go version
  become: yes
  command: go version

- name: Install NVM
  become: yes
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

- name: Load NVM in current shell session
  become: yes
  shell: >
    source ~/.nvm/nvm.sh &&
    echo "source ~/.nvm/nvm.sh" >> /home/{{ new_username }}/.bashrc
